---
- name: Deploy Medical Management System
  hosts: localhost
  vars:
    ansible_python_interpreter: /home/vedang/ansible_venv/bin/python3
  tasks:
    - name: Ensure old containers are removed
      community.docker.docker_compose_v2:
        project_name: medical_management
        state: absent
        project_src: /home/jenkins/devopsprjv1
      ignore_errors: yes
    - name: Run Docker Compose
      community.docker.docker_compose_v2:
        project_name: medical_management
        state: present
        build: always
        project_src: /home/jenkins/devopsprjv1
    - name: Wait for application to be ready
      wait_for:
        host: localhost
        port: 8080
        state: started
        timeout: 30
    - name: Verify application
      uri:
        url: http://localhost:8080/index.php
        status_code: 200
      register: result
    - name: Display verification result
      debug:
        msg: "Application is running: {{ result.status }}"